# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""A library of policy implementations keyed by ``strategy`` tag.

The heuristic SWE Agent maps a ChangeRequest's ``strategy`` tag to one of these
source bodies and writes it into the Planner. The LLM SWE Agent instead
generates its own source, so this library is only the deterministic path.

Each value is the *full* source of a policy module implementing ``decide(ctx)``.
"""

from __future__ import annotations

_HEADER = (
    "# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & "
    "AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    '"""Autoscaling policy under test (generated by the SWE Agent)."""\n\n\n'
)

# Reactive threshold — same behaviour as the seed. Kept so "no-op" requests are valid.
REACTIVE_THRESHOLD = _HEADER + (
    "def decide(ctx) -> int:\n"
    "    target = ctx.current_replicas\n"
    "    if ctx.utilization > 0.9:\n"
    "        target += 1\n"
    "    elif ctx.utilization < 0.5:\n"
    "        target -= 1\n"
    "    return max(1, min(ctx.max_replicas, target))\n"
)

# Hysteresis — scale up eagerly, scale down conservatively to stop flapping and
# the SLA hits that come with it. Also sizes the up-step to the actual gap.
HYSTERESIS = _HEADER + (
    "def decide(ctx) -> int:\n"
    "    need = ctx.offered_rps / max(1e-9, ctx.per_replica_rps)\n"
    "    target = ctx.current_replicas\n"
    "    if ctx.utilization > 0.80:\n"
    "        # jump straight to what the current load needs, with headroom\n"
    "        target = int(need * 1.15) + 1\n"
    "    elif ctx.utilization < 0.45:\n"
    "        # release capacity one replica at a time\n"
    "        target = ctx.current_replicas - 1\n"
    "    return max(1, min(ctx.max_replicas, target))\n"
)

# Predictive EMA — forecast next step's load from a short trend and pre-provision
# so replicas are already warm when a burst lands (the provisioning lag is the
# whole game in the arena).
PREDICTIVE_EMA = _HEADER + (
    "def decide(ctx) -> int:\n"
    "    hist = ctx.recent_rps or [ctx.offered_rps]\n"
    "    # exponential moving average of recent load\n"
    "    ema = hist[0]\n"
    "    for x in hist[1:]:\n"
    "        ema = 0.5 * x + 0.5 * ema\n"
    "    # extrapolate the local trend one step ahead\n"
    "    trend = hist[-1] - hist[0] if len(hist) > 1 else 0.0\n"
    "    forecast = max(ctx.offered_rps, ema + 0.5 * trend)\n"
    "    need = forecast / max(1e-9, ctx.per_replica_rps)\n"
    "    target = int(need * 1.15) + 1\n"
    "    return max(1, min(ctx.max_replicas, target))\n"
)

# Predictive + hysteresis — forecast to provision ahead, but damp scale-downs so
# a brief dip does not shed capacity right before the next burst.
PREDICTIVE_HYSTERESIS = _HEADER + (
    "def decide(ctx) -> int:\n"
    "    hist = ctx.recent_rps or [ctx.offered_rps]\n"
    "    ema = hist[0]\n"
    "    for x in hist[1:]:\n"
    "        ema = 0.5 * x + 0.5 * ema\n"
    "    trend = hist[-1] - hist[0] if len(hist) > 1 else 0.0\n"
    "    forecast = max(ctx.offered_rps, ema + 0.6 * trend)\n"
    "    need = forecast / max(1e-9, ctx.per_replica_rps)\n"
    "    want = int(need * 1.2) + 1\n"
    "    if want >= ctx.current_replicas:\n"
    "        target = want  # scale up immediately toward the forecast\n"
    "    else:\n"
    "        # scale down at most one replica per step (conservative)\n"
    "        target = ctx.current_replicas - 1\n"
    "    return max(1, min(ctx.max_replicas, target))\n"
)

STRATEGIES = {
    "reactive_threshold": REACTIVE_THRESHOLD,
    "hysteresis": HYSTERESIS,
    "predictive_ema": PREDICTIVE_EMA,
    "predictive_hysteresis": PREDICTIVE_HYSTERESIS,
}

# Order the heuristic Research Lead walks through when proposing changes.
STRATEGY_BACKLOG = [
    (
        "hysteresis",
        "Reactive per-step +/-1 scaling flaps and lags bursts.",
        "Replace the +/-1 threshold logic with hysteresis: on high utilization "
        "jump straight to the replica count the current load needs (with ~15% "
        "headroom), and only release capacity one replica at a time.",
    ),
    (
        "predictive_ema",
        "Even right-sized reactive scaling arrives one provisioning-lag too late "
        "for bursts.",
        "Forecast next-step load with an EMA of recent RPS plus a trend term and "
        "pre-provision to the forecast so replicas are warm before the burst lands.",
    ),
    (
        "predictive_hysteresis",
        "Prediction helps on the way up but a brief dip still sheds capacity right "
        "before the next burst.",
        "Combine the EMA/trend forecast with damped scale-downs (at most one "
        "replica removed per step) to hold capacity through short dips.",
    ),
]
